def print_menu():
    print (30 * "-" , "MENU" , 30 * "-")
    print ("1. Display the original image")
    print("2. Display the matrixes of brightness for the original image")
    print("3. Display the histogram")
    print("4. Binarization")
    print("5. Convert to grayscale")
    print("6. Negative")
    print("7. Use mask 'South' ")
    print("8. Use mask 'South-East' ")
    print ("9. Exit")
    print (67 * "-")